name: Demo to create automatic PR

on:
  push:
    branches:
      - master
      - dev

  pull_request_target:
    types: [opened]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: dev
          title: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: ${{ env.GIT_COMMIT_MESSAGE_BODY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false

      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Workflow
          column-name: To do
          issue-number: ${{ github.event.number }}
